### ISSUE TITLE
rule to build a new container

### ISSUE THREAD

**Issue by matteodelucchi** [furrer-lab/r-containers#12]
Based on Description file, check if a docker image already exists with the required information. Conditionally build a new one. This is an extension of issue #11 where the description file is being parsed to get the package name.

**Comment by matteodelucchi** [comment]
Just checking in if there is any progress on this. I added a new package (`microbenchmark`) to the DESCRIPTION file, causing issues since it has not been installed in the docker file.

Sidenote: This issue relates also to #6.

**Comment by j-i-l** [comment]
This will depend on the decision of furrer-lab/devel-abn#113

**Comment by matteodelucchi** [comment]
simply update the r-container documentation and close this.

**Comment by j-i-l** [comment]
Actually, we could choose a middle ground and rebuild the containers once per month, automatically incrementing the version.

For this we might switch to the semver compliant [calver](https://calver.org/) versioning and change the logic from `on-push-tag` to `on-push-workflowdispatch` which will allow us to start the pipeline manually. We can then add an `on-schedule-cron` running once a month.

Then we can always automatically increment the claver version, thus leading to monthly updated containers and more frequent ones whenever we push to master.
